services:

  gateway_server:
    container_name: gateway_server
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gateway_service

  gateway_service:
    container_name: gateway_service
    restart: always
    build:
      context: ./gateway
      dockerfile: Dockerfile
    volumes:
      - ./gateway:/var/www/html:delegated
    depends_on:
      - gateway_cache
      - users_service
      - finances_service
      # - auth
      # - analytics

  gateway_cache:
    container_name: gateway_cache
    image: redis:latest
    volumes:
      - gateway_redis_volume:/data
    ports:
      - "6379:6379"

  users_server:
    container_name: users_server
    restart: always
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./users/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - users_service

  users_service:
    container_name: users_service
    restart: always
    build:
      context: ./users
      dockerfile: Dockerfile
    volumes:
      - ./users:/var/www/html:delegated
    depends_on:
      - users_database

  users_database:
    container_name: users_database
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=expensitor_users
    volumes:
      - users_database_volume:/var/lib/mysql
    ports:
      - "3306:3306"

  finances_server:
    container_name: finances_server
    restart: always
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./finances/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - finances_service

  finances_service:
    container_name: finances_service
    restart: always
    build:
      context: ./finances
      dockerfile: Dockerfile
    volumes:
      - ./finances:/var/www/html:delegated
    depends_on:
      - finances_database

  finances_database:
    container_name: finances_database
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - finances_database_volume:/data/db

volumes:
  gateway_redis_volume:
  users_database_volume:
  finances_database_volume:

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "3000:8081"

  # auth:
  #   build:
  #     context: ./auth
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./auth:/var/www/html
  #   environment:
  #     - DATABASE_HOST=auth-db
  #     - DATABASE_USER=root
  #     - DATABASE_PASSWORD=root
  #     - DATABASE_NAME=auth
  #   depends_on:
  #     - auth-db

  # auth-db:
  #   image: mariadb:latest
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=auth

  # analytics:
  #   build:
  #     context: ./analytics
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./analytics:/var/www/html
  #   environment:
  #     - MONGO_URI=mongodb://analytics-db:27017/analytics
  #   depends_on:
  #     - analytics-db

  # analytics-db:
  #   image: mongo:latest